# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2017

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: false

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  Tags: /tags/
  Categories: /categories/
  About: /about/

# ===========================================
# Theme Settings
# ===========================================
# color: default | mint green | cobalt blue | hot pink | dark violet
color: default

# default page mode: default | archives
mode: default

toc: true

# jQuery fancybox
fancybox: true

pjax: true

# LaTeX support (via MathJax)
latex: true

copyright:
  enable: false
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank"> 知识共享署名 - 非商业性使用 4.0 国际许可协议 </a>'

reward:
  enable: false
  qrCode:
    wechat:
    alipay:

# ===========================================
# Social links Settings
# ===========================================
social:
  email: yg_wen@126.com
  stack-overflow:
  twitter:
  facebook:
  linkedin:
  google:
  github: https://github.com/wenyg
  weibo:
  zhihu:
  douban:
  pocket:
  tumblr:
  instagram:

# ===========================================
# Third Party Services Settings
# ===========================================

# LeanCloud
leancloud:
  app_id:
  app_key:

# Baidu Analytics
baidu_analytics: 46dc9ceed870eaf1f7b89f98259df601
# Baidu Verification
baidu_verification:

# Google Analytics
google_analytics:
# Google Verification
google_verification:

# Disqus
disqus_shortname:

#Changyan
changyan:
  appid:
  appkey:

#LiveRe
livere_datauid:

# ===========================================
# Version
# ===========================================
version: 2.11.0

resume:
  name: 温阳光
  jobtitle: C/C++ 资深开发工程师
  portrait: /d/img/resume/wenyg.jpg # author's portrait
  contact:
    - icon: fa-envelope
      text: yg_wen@126.com
    - icon: fa-phone-square
      text: "17521662505"
    - icon: fa-home
      text: "www.winn.cc"
      link: "https://www.winn.cc"
    - icon: fa-github
      text: github/wenyg
      link: "https://github.com/wenyg"
  education:
    - university: 中原工学院
      duration: 2013/9 ~ 2017/5
      location:  软件工程
      # major: 软件工程
  experience:
    - title: 软件工程师
      duration: 2023.5 ~ 至今
      company: 上海华人运通 (高合汽车)
      description: >
        1. 负责公司车路协同路侧通信设备运维管理平台 RSU 接口开发。 <br>
        2. 参与 ADAS 智能驾驶地图，定位，感知，融合，预测内部可视化工具研发。

    - title: 软件工程师
      duration: 2019.4 ~ 2023.5 (4 年)
      company: 合合信息 (扫描全能王)
      description: >
        1. 负责公司 CUDA/CPU 的 OCR 服务系统集成交付。<br>
        2. 负责公司内部低代码构建平台，容器管理平台的设计以及研发。<br>
        3. 参与公司内部其他平台的对接以及需求评审。<br>
        4. 负责私有云授权加密系统设计以及研发。<br>
        5. 内部团队效率工具研发。

    - title: 软件工程师
      duration: 2018.6 ~ 2019.3 (9 月)
      company: 上海金卓科技网络
      description: >
        1. 负责无线自组网终端网络协议仿真。 <br>
        2. 负责终端协议栈开发，参与网络层路由算法，链路层时隙分配实现。
    - title: 软件工程师
      duration: 2016.6-2018.5 (2 年)
      company: 北京云起龙骧科技
      description: >
        1. 负责智能 DNS 服务器项目 <br>
        2. 负责邮件推送系统
  projects:
    - name: 车路协同路侧通信设备运维管理平台
      contribution: C/C++ 工程师  
      description: >
        项目描述:<br>
        &nbsp;&nbsp;&nbsp;&nbsp; 按照中国通信标准化协会发布的平台要求实现 RSU 运维管理平台接口。包含设备、配置、告警、性能、OTA、数据统计等功能模块。
        <br> 项目架构:<br>
        &nbsp;&nbsp;&nbsp;&nbsp; RSU 采用 MQTT 与管理平台进行通信，用 fdbus 与 RSU 其他模块进行数据交互。采用 Protobuf 进行数据序列化。采用 Google Test 做单元测试。
        <br> 技术职责:<br>
        &nbsp;&nbsp;&nbsp;&nbsp;1. 平台需求分析，方案制定以及代码设计和实现。<br>
        &nbsp;&nbsp;&nbsp;&nbsp;2. 自动化测试程序设计与实现。
    - name: 车路协同路侧通信设备运维管理平台
      contribution: C/C++ 工程师  
      description: >
        项目描述:<br>
        &nbsp;&nbsp;&nbsp;&nbsp; 与智能驾驶团队地图，定位，感知，融合，预测部门配合，实现其数据处理以及可视化展示。
        <br> 技术职责:<br>
        &nbsp;&nbsp;&nbsp;&nbsp;1. ROS, Protobuf, Struct 消息定义与转换。<br>
        &nbsp;&nbsp;&nbsp;&nbsp;2. 自动化测试程序设计与实现。
    
    - name: MOSS 构建平台
      description: >
        项目描述:<br>
        &nbsp;&nbsp;&nbsp;&nbsp; 该项目主要为了解决旧平台算法接口到商业化中间的流程过长，交付缓慢的问题。该平台通过模块与业务解耦，低代码任务编排，可以快速的构建业务镜像。支持 x86 和 ARM 架构。版本发布耗时由 1~2 天降低至 1~2 小时。目前公司内超过 80% 的开发者在使用该平台进行产品上线以及项目交付。累计 30+ 算法模块，构建 80+ 产品，发布 400+ 版本。
        <br> 项目架构:<br>
        &nbsp;&nbsp;&nbsp;&nbsp; 模块部分用 Google Test 做单元测试，gcovr 做代码覆盖率测试，Gitlab CI 做自动化集成。平台部分用 Nginx + Lua + PostgreSQL + Argo Workflow + Kaniko 处理前端业务逻辑以及镜像构建。业务镜像内部框架使用 Boost 处理 http 请求，taskflow 做模块编排，pybind11 做 python 模块接入。技术职责:
        <br> 技术职责:<br>
        &nbsp;&nbsp;&nbsp;&nbsp;1. 核心模块架构设计，技术选型以及难关攻克。<br>
        &nbsp;&nbsp;&nbsp;&nbsp;2. 低代码模块编排的设计与实现。<br>
        &nbsp;&nbsp;&nbsp;&nbsp;3. 单元测试，代码覆盖率测试脚手架设计与实现。<br>
        &nbsp;&nbsp;&nbsp;&nbsp;4. C++ 包管理器的设计与实现以及技术迭代。<br>
        &nbsp;&nbsp;&nbsp;&nbsp;5. 参与内部发布平台 / 测试平台需求评审，以及自动化流程对接。<br>
        &nbsp;&nbsp;&nbsp;&nbsp;6. 跨部门合作，沟通交流，项目推广，以及技术培训。
      contribution: Linux C 研发工程师
    - name: 授权加密系统
      description: >
        项目描述:<br>
        &nbsp;&nbsp;&nbsp;&nbsp; 该项目主要为了保护公司知识产权，绑定硬件信息的方式，将产品授权与机器进行绑定，防止私有化产品被盗刻复刻。有许可证中心授权服务和序列号授权两种方式。累计发放许可证 6000+ 个。
        <br> 项目架构:<br>
        &nbsp;&nbsp;&nbsp;&nbsp; 授权服务器采用 Libevent 处理网络请求，用 OpenSSL 做加解密以及校验，同时通过代码混淆，加壳等步骤对程序进行加固。
        <br> 技术职责:<br>
        &nbsp;&nbsp;&nbsp;&nbsp; 负责整个项目的架构设计，加解密策略，传输协议等设计与研发。
      contribution: 项目负责人
    - name: 智能 DNS 服务器
      contribution: Linux C 研发工程师
      description: >
        项目描述:<br>
        &nbsp;&nbsp;&nbsp;&nbsp; 智能 DNS 服务器，在传统的 DNS 基础功能上添加了智能解析，可视化管理等功能技术架构：
        由 Apache + CGI 处理前端请求，通过 UNIX 域套接字与 DNS 服务通讯进行域名配置。其中 DNS 服务器采用 epoll 多路复用处理 DNS 请求，用哈希表实现域名快速查找，用 radix tree 实现 IP 库的建立查找与匹配。
        <br> 技术职责：<br>
        &nbsp;&nbsp;&nbsp;&nbsp;1. 负责 DNS 服务主程代码。<br>
        &nbsp;&nbsp;&nbsp;&nbsp;2. DNS 协议编解码的实现。<br>
        &nbsp;&nbsp;&nbsp;&nbsp;3. 负责 IP 库的实现以及维护。<br>

  skills:
    - title: 1. 熟练掌握 <b>C/C++</b>, 熟悉 <b> 面向过程 / 面向对象 / 泛型编程 </b> 等思想，7 年开发经验。
      items: xxx
    - title: 2. 熟悉 <b>Python/Shell/Lua</b> 脚本语言，了解 NodeJS, ReactJS 前端语言。
      items: xxx
    - title: 3. 擅长阅读源码，为开源项目 NS3, <b>Libevent</b>, Opentelementry 贡献过少量代码。
      items: xxx
    - items: xxx
      title: 4. 熟练 <b>Docker</b> 底层原理，熟悉 <b>Kubernetes</b>, Argo Wrokflow 基本操作。
    - items: xxxx
      title: 5. 熟悉 <b>TCP/IP</b> 协议栈，熟悉 <b>HTTP, SSL, DNS</b>, MQTT 等网络协议。
    - items: xxxx
      title: 6. 熟悉 Linux 下 <b> 网络编程 </b>, <b> 多线程编程 </b>, <b> 共享内存 </b>, <b> 进程间通信 </b>。
    - items: xxxx
      title: 7. 熟练掌握 Linux 下 <b>gcc cmake</b> 构建系统，熟悉 <b>gdb</b> 调试工具。
    - items: xxxx
      title: 8. 了解 Linux <b> 内核进程管理，内存管理，进程调度 </b > 实现机制。
    - items: xxxx
      title: 9. 熟悉程序的的 <b> 编译 </b>, <b> 汇编 </b>, <b> 链接 </b>, <b> 装载过程 </b>, 了解交叉编译。
    - items: xxxx
      title: 10. 负责过多个中小型项目软件项目功能 / 模块 /<b> 架构设计 </b>, 以及相关维护，产品迭代工作。
    - items: xxxx
      title: 11. 熟悉软件单元测试，TDD <b> 测试驱动开发 </b>。
    - items: xxxx
      title: 12. 擅长于 <b> 文档编写 </b>, 在目前公司内留下项目文档，教程，技术博客等累计字数 10W+。
    - items: xxxx
      title: 13. 擅长于 <b> 知识分享 </b>, 在历任公司内部进行数十次的技术专题分享。
